# Generated by Django 2.0.13 on 2019-06-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post10',
            name='result',
            field=models.IntegerField(),
        ),
    ]
